Task is done
mate-academy/react_autocomplete pull request #136
Opened 2023-07-22 17:55 UTC by Konsttantin

[DEMO LINK](https://Konsttantin.github.io/react_autocomplete/)

2023-07-23 09:05 UTC, TarasHoliuk requested changes

2023-07-23 09:05 UTC, TarasHoliuk commented on src/App.tsx
> +import { Autocomplete } from './components/Autocomplete';
add this file to git to make review possible

P.S. Don't use `git commit -am 'your message example'` command - it doesn't add new files
better use `git add .` to add all files (or for example `git add src/components/Autocomplete.tsx` to add 1 file you need) and then just `git commit -m 'message'`

2023-07-24 08:30 UTC, polosanya approved these changes
Good job!

2023-07-24 08:30 UTC, polosanya commented on src/App.tsx
> +          'No selected person'
```suggestion
        {selectedPerson 
          ? `${selectedPerson.name} (${selectedPerson.born} - ${selectedPerson.died})`
          : 'No selected person'
```

2025-01-19 15:37 UTC, closed without merging