something terrible, just to test
mate-academy/react_autocomplete pull request #182
Opened 2023-08-23 21:14 UTC by aliliolek

[DEMO LINK](https://aliliolek.github.io/react_autocomplete/)

2023-08-24 06:42 UTC, maxim2310 requested changes
Great job overall! Just couple tiny things needs to be fixed before approval)

2023-08-24 06:42 UTC, maxim2310 commented on src/App.tsx
> +    = useState<Person | null>(peopleFromServer[0]);
you must not select person by default 
![image](https://github.com/mate-academy/react_autocomplete/assets/96265844/efc0febc-b44a-4c0d-8ccd-7cae40889add)

2023-08-24 06:42 UTC, maxim2310 commented on src/App.tsx
> +    debounce(setQuery, 1000),
make this delay is smaller, about 0.8s or 0.5s

2023-08-24 06:42 UTC, maxim2310 commented on src/App.tsx
> +            }}
to much actions, move to separate func

2023-08-24 06:42 UTC, maxim2310 commented on src/App.tsx
> +              )}
why do you need classnames here?

2023-08-24 06:42 UTC, maxim2310 commented on src/App.tsx
> +            "
```suggestion
          className="dropdown-menu dropdown-menu--height"
```

2023-09-05 14:36 UTC, mykhalenych requested changes
Nice work, but fix small suggestions

2023-09-05 14:36 UTC, mykhalenych commented on src/App.tsx
> +import debounce from 'lodash.debounce';
<img width="909" alt="Screenshot 2023-09-05 at 17 31 28" src="https://github.com/mate-academy/react_autocomplete/assets/53228259/69d4e542-432a-42c5-b143-932a5c366d37">
you are using lodash but didn't install module in package.json
also try to write your own debounce function

2023-09-05 14:36 UTC, mykhalenych commented on src/App.tsx
> +    setIsActive(clickCount % 2 === 0);
why do you need set addition state after toggle?
`const isActive = clickCount % 2 === 0`

2023-10-23 21:02 UTC, closed without merging