init
mate-academy/react_autocomplete pull request #186
Opened 2023-08-26 13:33 UTC by MaksymKos

https://maksymkos.github.io/react_autocomplete/

2023-08-26 14:31 UTC, VitaliyBondarenko1982 requested changes
Dropdown shouldn't be visible when input does not in focus
![chrome-capture-2023-7-26 (2)](https://github.com/mate-academy/react_autocomplete/assets/33029864/84b2a19b-d364-4d21-872a-9e922b2c8f1e)

2023-08-26 14:31 UTC, VitaliyBondarenko1982 commented on src/DropDown.tsx
> +          }}
move to separate function and pass referense on it here

2023-08-26 14:31 UTC, VitaliyBondarenko1982 commented on src/DropDown.tsx
> +    setIsDropdownShown(true);
show dropdown on onFocus event

2023-08-28 06:48 UTC, etojeDenys requested changes
still can reproduce it
<img width="586" alt="image" src="https://github.com/mate-academy/react_autocomplete/assets/70220667/9322a6cc-e5a0-45e6-b87b-0ea545b958e9">
feel free to ask in the chat if you have some problems

2023-08-28 06:48 UTC, etojeDenys commented on src/DropDown.tsx
> +          onChange={(event) => handleQueryChange(event)}
```suggestion
          onChange={handleQueryChange}
```
we can simplify it

2023-08-28 06:48 UTC, etojeDenys commented on src/DropDown.tsx
> +                className={`dropdown-item ${person.sex === 'm' ? 'has-text-link' : 'has-text-danger'}`}
let's use className package for such cases

2023-08-28 07:08 UTC, etojeDenys requested changes
https://github.com/mate-academy/react_autocomplete/assets/70220667/5b0f97f7-441a-46da-8cf2-add7e75561b7

cannot select the person

2023-08-28 07:08 UTC, etojeDenys commented on src/DropDown.tsx
> +                  person.sex === 'f' && 'has-text-danger'
```suggestion
                   'has-text-link': person.sex === 'm',
                   'has-text-danger': person.sex === 'f'
```

2023-08-28 17:41 UTC, etojeDenys requested changes
still can reproduce the bug

2023-08-28 17:47 UTC, etojeDenys approved these changes
lgtm

2024-10-14 06:23 UTC, closed without merging