stage-1
mate-academy/react_autocomplete pull request #348
Opened 2023-11-05 17:55 UTC by no4kar

[DEMO LINK](https://no4kar.github.io/react_autocomplete/)

2023-11-06 07:48 UTC, volodymyr-soltys97 requested changes
Good job
The selected person must also be shown in the input
<img width="765" alt="image" src="https://github.com/mate-academy/react_autocomplete/assets/64750958/49d89a9d-1820-45a0-96a2-55f5b22e5a22">

2023-11-06 17:42 UTC, Esceype requested changes
GJ!
But it should be a separate component. The main idea to have ability to use this component everywhere in your project, like imagine that you have big project and you want to reuse this component everywhere. Check the MUI implementation(you have link in the description to this task). That is the main idea of the task to create a separate component that you could be able to reuse.

About styles:
The row that is on hover should be highlighted.
Add cross to clean selected item from search
Add arrow-down like it is in Bulma or in MUI.

2023-11-07 16:12 UTC, sTorba24 requested changes
Almost good! Lets implement this part
![image](https://github.com/mate-academy/react_autocomplete/assets/55200530/4e193a04-ceab-4c25-bfdc-6b8d170770a0)

2023-11-08 12:05 UTC, anastasiiavorobiova requested changes
Great work! Try to fix your tests 
<img width="1319" alt="Screenshot 2023-11-08 at 14 04 06" src="https://github.com/mate-academy/react_autocomplete/assets/135232001/717cdb81-3730-4148-b9e2-b4799c645245">

2023-11-08 16:19 UTC, sTorba24 approved these changes

2025-04-22 16:54 UTC, closed without merging