react_autocomplete
mate-academy/react_autocomplete pull request #502
Opened 2024-02-12 17:43 UTC by TetianaMD

[DEMO LINK](https://TetianaMD.github.io/react_autocomplete/)

2024-02-12 18:07 UTC, SanyaBratashchuk requested changes
![image](https://github.com/mate-academy/react_autocomplete/assets/97547824/687ed485-a9e7-4a85-bbf6-4788dc8acfc9)
search doesn't work

2024-02-13 16:31 UTC, etojeDenys commented on src/components/Autocomplete.tsx
> +    debounce(() => setShowAllPeople(true), 300),
<img width="717" alt="image" src="https://github.com/mate-academy/react_autocomplete/assets/70220667/903cb693-c6da-4baa-b946-9b0562b3abad">

2024-02-13 18:29 UTC, SanyaBratashchuk requested changes

2024-02-13 18:29 UTC, SanyaBratashchuk commented on src/components/Autocomplete.tsx
> +  const debouncedApplyQuery = debounce(applyQuery, 1000);
![image](https://github.com/mate-academy/react_autocomplete/assets/97547824/e49ae3f6-b37f-49d9-b44f-1081b8079ce9)

2024-02-14 07:41 UTC, volodymyr-soltys97 requested changes
To improve:
When you click on a person from the list, nothing happens, you need to show the person in the input and change the text above
<img width="470" alt="image" src="https://github.com/mate-academy/react_autocomplete/assets/64750958/d2b08588-61be-49de-9cb1-723bdb70070f">

2024-02-14 07:41 UTC, volodymyr-soltys97 commented on src/App.tsx
> +          {selectedPerson ? `${name} (${born} - ${died})` : 'No selected person'}
Consider will be better if you move this logic to the variable and use it here

2024-02-14 07:41 UTC, volodymyr-soltys97 commented on src/components/Autocomplete.tsx
> +import debounce from 'lodash.debounce';
Fix it
<img width="866" alt="image" src="https://github.com/mate-academy/react_autocomplete/assets/64750958/661c5883-b543-4364-9fde-b00ca11f20c7">

2024-02-14 07:41 UTC, volodymyr-soltys97 commented on src/components/Autocomplete.tsx
> +            {filteredPersons.length > 0
```suggestion
            {!!filteredPersons.length
```

2024-02-14 13:53 UTC, anastasiiavorobiova requested changes
Consider hiding the list of suggestions when the input is not focused

2024-02-14 16:34 UTC, closed without merging