solution
mate-academy/react_autocomplete pull request #74
Opened 2023-07-03 12:48 UTC by Gosyav

https://vo7kov.github.io/react_autocomplete/

2023-07-03 14:20 UTC, mykhalenych requested changes

2023-07-03 14:20 UTC, mykhalenych commented on package.json
> +    "lodash.debounce": "^4.0.8",
how about an idea to write debounce by yourself?

2023-07-03 14:20 UTC, mykhalenych commented on src/components/dropdown/Dropdown.tsx
> +  const [people] = useState(options);
why do need useState here without setter?

2023-07-03 14:20 UTC, mykhalenych commented on src/components/dropdown/Dropdown.tsx
> +
```suggestion
```

2023-07-03 14:20 UTC, mykhalenych commented on src/components/dropdown/Dropdown.tsx
> +  const hadnleItemClick = (
```suggestion
  const handleItemClick = (
```

2023-07-03 14:20 UTC, mykhalenych commented on src/components/dropdown/Dropdown.tsx
> +  const applyQuery = useCallback(debounce(setAppliedQuery, delay), []);
```suggestion
```

2023-07-03 14:20 UTC, mykhalenych commented on src/components/dropdown/Dropdown.tsx
> +    applyQuery(event.target.value);
```suggestion
    debounce(setAppliedQuery, delay)
```

2023-07-04 07:14 UTC, etojeDenys requested changes

2023-07-04 07:14 UTC, etojeDenys commented on src/components/dropdown/Dropdown.tsx
> +                <div className="dropdown-item">
you forgot about key prop

2023-07-04 07:14 UTC, etojeDenys commented on src/components/dropdown/Dropdown.tsx
> +  const applyQuery = useCallback(debounce(setAppliedQuery, delay), []);
why do we still need this function if we can just call debounce in handleInputChange

2023-07-04 10:10 UTC, IvanFesenko approved these changes

2025-07-07 13:33 UTC, closed without merging