solution
mate-academy/react_autocomplete pull request #97
Opened 2023-07-13 13:35 UTC by DanyloPasko

[DEMO LINK](https://DanyloPasko.github.io/react_autocomplete/)

2023-07-13 18:56 UTC, polosanya requested changes
1. It would be great to show all people on focus initially
![image](https://github.com/mate-academy/react_autocomplete/assets/96409563/fa1ddb95-e09e-4cc2-8749-1a9e488a8878)
2. Also, the list should be closed when focus is lost (onBlur)
![image](https://github.com/mate-academy/react_autocomplete/assets/96409563/b9c76950-2ff7-453e-a35d-fe95a614284b)

2023-07-14 08:20 UTC, volodymyr-soltys97 requested changes
Good job
But let's make your code perfect

2023-07-14 08:20 UTC, volodymyr-soltys97 commented on src/App.tsx
> +    // setAppliedQuery('');
The line 'setAppliedQuery('');' is commented out. If this line is not needed, consider removing it to clean up the code.

2023-07-14 08:20 UTC, volodymyr-soltys97 commented on src/App.tsx
> +  const [delay] = useState(1000);
The delay is hardcoded and is not customizable as required in the task. Consider passing delay as a prop to the component or getting it from component's state.

2023-07-14 16:50 UTC, VitaliyBondarenko1982 approved these changes

2023-07-14 16:50 UTC, VitaliyBondarenko1982 commented on src/App.tsx
> +import debounce from 'lodash.debounce';
```suggestion
import { debounce } from 'lodash';
```

2025-06-13 14:19 UTC, closed without merging